parameters:
    redking_parse.fos_user.manager.class: 'Redking\ParseBundle\Bridge\FOSUser\UserManager'
    redking_parse.fos_user.base_manager.class: 'Redking\ParseBundle\Bridge\FOSUser\BaseUserManager'
    redking_parse.fos_user.mailer.class: 'Redking\ParseBundle\Bridge\FOSUser\Mailer'

services:

### FOSUSER PARSE BRIDGE USER MANAGER ###
    redking_parse.fos_user.base_manager:
        class: "%redking_parse.fos_user.base_manager.class%"
        public: false
        arguments: 
            - "@security.encoder_factory"
            - "@fos_user.util.username_canonicalizer"
            - "@fos_user.util.email_canonicalizer"
            - "@redking_parse.manager"
            - "%fos_user.model.user.class%"
    redking_parse.fos_user.manager:
        class: "%redking_parse.fos_user.manager.class%"
        parent: redking_parse.fos_user.base_manager

### FOSUSER PARSE BRIDGE MAILER ###
    redking_parse.fos_user.mailer: 
        arguments: 
            - "@mailer"
            - "@router"
            - "@twig"
            - 
                from_email: 
                    confirmation: "%fos_user.registration.confirmation.from_email%"
                    resetting: "%fos_user.resetting.email.from_email%"
                template:
                    resetting: "%fos_user.resetting.email.template%"
                    confirmation: "%fos_user.registration.confirmation.template%"
        class: "%redking_parse.fos_user.mailer.class%"
        public: false
