parameters:
    redking_parse.fos_user.mailer.class: 'Redking\ParseBundle\Bridge\FOSUser\Mailer'

services:
    ### FOSUSER PARSE BRIDGE MAILER ###
    redking_parse.fos_user.mailer: 
        arguments: 
            - "@mailer"
            - "@router"
            - "@twig"
            - 
                from_email: 
                    confirmation: "%fos_user.registration.confirmation.from_email%"
                    resetting: "%fos_user.resetting.email.from_email%"
                template:
                    resetting: "%fos_user.resetting.email.template%"
                    confirmation: "%fos_user.registration.confirmation.template%"
        class: "%redking_parse.fos_user.mailer.class%"
        public: false
