services:
    # Form Type
    redking_parse.form.object:
        class: Redking\ParseBundle\Form\Type\ObjectType
        tags:
            - {name: form.type, alias: object}
        arguments:
            - "@doctrine_parse"
    redking_parse.form.file:
        class: Redking\ParseBundle\Form\Type\ParseFileType
        tags:
            - {name: form.type, alias: parse_file}
        arguments:
            - "@redking_parse.manager"


    # Form Type Guesser
    form.type_guesser.doctrine.parse:
        class: Redking\ParseBundle\Form\DoctrineParseTypeGuesser
        tags:
            - {name: form.type_guesser}
        arguments:
            - "@doctrine_parse"
    
