parameters:
    doctrine.parse.metadata.annotation.class: 'Redking\ParseBundle\Mapping\Driver\AnnotationDriver'
    doctrine.parse.metadata.yml.class: 'Redking\ParseBundle\Mapping\Driver\YamlDriver'
    doctrine.parse.metadata.driver_chain.class: 'Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain'
    doctrine.parse.proxy_cache_warmer.class: 'Redking\ParseBundle\CacheWarmer\ProxyCacheWarmer'
    doctrine.parse.data_collector.class: 'Redking\ParseBundle\DataCollector\SimpleDataCollector'
    doctrine.parse.logger.class: 'Redking\ParseBundle\Logger\Logger'
    doctrine.parse.logger.aggregate.class: 'Redking\ParseBundle\Logger\AggregateLogger'
    doctrine.parse.listeners.resolve_target_object.class: 'Redking\ParseBundle\Tools\ResolveTargetObjectListener'
    parse_authenticator.class: 'Redking\ParseBundle\Security\ParseAuthenticator'
    doctrine_parse.validator.unique.class: 'Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator'
    doctrine_parse.fixtures_dirs: []
    doctrine_parse.session_storage.class: 'Redking\ParseBundle\Bridge\Parse\Storage\ParseSessionStorage'

services:
    # Registry
    doctrine_parse:
        class: Redking\ParseBundle\Registry
        arguments:
            - "@service_container"
            - "redking_parse.manager"

    # Manager
    redking_parse.manager:
        class: Redking\ParseBundle\ObjectManager
        arguments:
            - "@redking_parse.configuration"
            - "@redking_parse.event_manager"
            - "@doctrine_parse.session_storage"

    redking_parse.event_manager:
        class: Doctrine\Common\EventManager

    redking_parse.configuration:
        class: Redking\ParseBundle\Configuration
        public: false

    doctrine.parse.metadata.annotation_reader:
        alias: annotation_reader

    # Generate proxies classes on cache
    redking_parse.proxy_cache_warmer:
        class: %doctrine.parse.proxy_cache_warmer.class%
        public: false
        arguments:
            - "@redking_parse.manager"
        tags:
            - {name: kernel.cache_warmer}

    # logger
    redking_parse.logger.aggregate:
        class: %doctrine.parse.logger.aggregate.class%
        public: false

    redking_parse.logger:
        class: %doctrine.parse.logger.class%
        public: false
        arguments:
            - "@logger"
        tags:
            - {name: monolog.logger, channel: parse}

    # listeners
    doctrine.parse.listeners.resolve_target_object:
        class: %doctrine.parse.listeners.resolve_target_object.class%
        public: false

    # profiler
    redking_parse.data_collector:
        class: %doctrine.parse.data_collector.class%
        public: false
        arguments:
            - "@?debug.stopwatch"

    # sensio converter parameter
    redking_parse.converter.doctrine.parse:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments:
            - "@doctrine_parse"
        tags:
            - {name: request.param_converter, converter: doctrine.parse, priority: 1}

    # authenticator
    parse_authenticator:
        class:     "%parse_authenticator.class%"

    # validators
    doctrine_parse.validator.unique:
        class: %doctrine_parse.validator.unique.class%
        arguments:
            - "@doctrine_parse"
        tags:
            - {name: validator.constraint_validator, alias: doctrine_parse.unique}

    # parse session storage
    doctrine_parse.session_storage:
        class: %doctrine_parse.session_storage.class%
        arguments:
            - "@session"