language: php

services:
  - docker

php:
  - 5.6
  - 7.0

env: 
  - SYMFONY_VERSION=^2.8
  - SYMFONY_VERSION=^3.4

cache:
    directories:
        - $HOME/.composer/cache

before_install:
  - composer self-update
  - phpenv config-rm xdebug.ini || true
  - docker run -d -p 27017:27017 --name mongo mongo
  - docker run -d -e APP_ID=${DOCTRINE_PARSE_APP_ID} -e MASTER_KEY=${DOCTRINE_PARSE_MASTER_KEY} -e ALLOW_CLIENT_CLASS_CREATION=1 --link mongo --name parse-server -p 1337:1337 yongjhih/parse-server
  - composer require --no-update symfony/symfony:${SYMFONY_VERSION}

install: composer update --prefer-dist

script: vendor/bin/phpunit --debug

notifications:
  email:
    - damien.matabon@gmail.com
