<?php

namespace Redking\ParseBundle;

use Doctrine\Persistence\Mapping\Driver\MappingDriver;
use InvalidArgumentException;
use Psr\Cache\CacheItemPoolInterface;
use Redking\ParseBundle\Exception\RedkingParseException;
use Redking\ParseBundle\Mapping\DefaultNamingStrategy;
use Redking\ParseBundle\Mapping\DefaultObjectListenerResolver;

/**
 * Configuration container for the Doctrine DBAL.
 *
 * @since    2.0
 *
 * @author   Guilherme Blanco <guilhermeblanco@hotmail.com>
 * @author   Jonathan Wage <jonwage@gmail.com>
 * @author   Roman Borschel <roman@code-factory.org>
 *
 * @internal When adding a new configuration option just write a getter/setter
 *           pair and add the option to the _attributes array with a proper default value.
 */
class Configuration
{
    /**
     * Never autogenerate a proxy and rely that it was generated by some process before deployment.
     */
    public const AUTOGENERATE_NEVER = 0;

    /**
     * Always generates a new proxy class in every request.
     *
     * This is only sane during development.
     */
    public const AUTOGENERATE_ALWAYS = 1;

    /**
     * Autogenerate the proxy class when the file does not exist.
     *
     * This strategy causes a file exists call whenever any proxy is used the
     * first time in a request.
     */
    public const AUTOGENERATE_FILE_NOT_EXISTS = 2;

    /**
     * Generate the proxy classes using eval().
     *
     * This strategy is only sane for development.
     */
    public const AUTOGENERATE_EVAL = 3;

    /**
     * Array of attributes for this configuration instance.
     *
     * @var array
     */
    protected $_attributes = array();

    /** @var CacheItemPoolInterface|null */
    private $metadataCache;

    private ?string $proxyDir = null;

    private string $proxyNamespace = 'ParseProxies';

    private int $autoGenerateProxyClasses = self::AUTOGENERATE_FILE_NOT_EXISTS;

    private bool $useLazyGhostObject = false;

    public function __construct()
    {
    }

    /**
     * Adds a namespace under a certain alias.
     *
     * @param string $alias
     * @param string $namespace
     */
    public function addEntityNamespace($alias, $namespace)
    {
        $this->_attributes['entityNamespaces'][$alias] = $namespace;
    }

    /**
     * Resolves a registered namespace alias to the full namespace.
     *
     * @param string $entityNamespaceAlias
     *
     * @return string
     *
     * @throws ORMException
     */
    public function getEntityNamespace($entityNamespaceAlias)
    {
        if (!isset($this->_attributes['entityNamespaces'][$entityNamespaceAlias])) {
            throw new RedkingParseException("Unknown Entity namespace alias '$entityNamespaceAlias'.");
        }

        return trim($this->_attributes['entityNamespaces'][$entityNamespaceAlias], '\\');
    }

    /**
     * Sets the entity alias map.
     *
     * @param array $entityNamespaces
     */
    public function setEntityNamespaces(array $entityNamespaces)
    {
        $this->_attributes['entityNamespaces'] = $entityNamespaces;
    }

    /**
     * Retrieves the list of registered entity namespace aliases.
     *
     * @return array
     */
    public function getEntityNamespaces()
    {
        return $this->_attributes['entityNamespaces'];
    }

    /**
     * Sets the cache driver implementation that is used for metadata caching.
     *
     * @param MappingDriver $driverImpl
     *
     * @todo Force parameter to be a Closure to ensure lazy evaluation
     *       (as soon as a metadata cache is in effect, the driver never needs to initialize).
     */
    public function setMetadataDriverImpl(MappingDriver $driverImpl)
    {
        $this->_attributes['metadataDriverImpl'] = $driverImpl;
    }

    /**
     * Gets the cache driver implementation that is used for the mapping metadata.
     *
     * @return MappingDriver|null
     *
     * @throws ORMException
     */
    public function getMetadataDriverImpl()
    {
        return isset($this->_attributes['metadataDriverImpl'])
            ? $this->_attributes['metadataDriverImpl']
            : null;
    }

    /**
     * Sets naming strategy.
     *
     * @since 2.3
     *
     * @param DefaultNamingStrategy $namingStrategy
     */
    public function setNamingStrategy(DefaultNamingStrategy $namingStrategy)
    {
        $this->_attributes['namingStrategy'] = $namingStrategy;
    }

    /**
     * Gets naming strategy..
     *
     * @since 2.3
     *
     * @return NamingStrategy
     */
    public function getNamingStrategy()
    {
        if (!isset($this->_attributes['namingStrategy'])) {
            $this->_attributes['namingStrategy'] = new DefaultNamingStrategy();
        }

        return $this->_attributes['namingStrategy'];
    }

    /**
     * Sets the directory where proxy class files are generated.
     */
    public function setProxyDir(string $dir): void
    {
        $this->proxyDir = $dir;
    }

    /**
     * Gets the directory where proxy class files are generated.
     */
    public function getProxyDir(): ?string
    {
        return $this->proxyDir;
    }

    /**
     * Gets the namespace where proxy classes reside.
     */
    public function getProxyNamespace(): string
    {
        return $this->proxyNamespace;
    }

    /**
     * Sets the namespace where proxy classes reside.
     */
    public function setProxyNamespace(string $ns): void
    {
        $this->proxyNamespace = $ns;
    }

    /**
     * Returns the proxy class auto-generation mode.
     */
    public function getAutoGenerateProxyClasses(): int
    {
        return $this->autoGenerateProxyClasses;
    }

    /**
     * Sets the proxy class auto-generation mode.
     *
     * @throws InvalidArgumentException If an invalid mode was given.
     */
    public function setAutoGenerateProxyClasses(int $mode): void
    {
        if (! in_array($mode, [
            self::AUTOGENERATE_NEVER,
            self::AUTOGENERATE_ALWAYS,
            self::AUTOGENERATE_FILE_NOT_EXISTS,
            self::AUTOGENERATE_EVAL,
        ], true)) {
            throw new InvalidArgumentException(sprintf('Invalid proxy generation mode "%d".', $mode));
        }

        $this->autoGenerateProxyClasses = $mode;
    }

    /**
     * Toggles the use of native PHP 8.4 lazy ghost objects.
     *
     * When enabled, the bundle relies on \ReflectionClass::newLazyGhost() instead of
     * generating a proxy class via symfony/var-exporter. Requires PHP 8.4+.
     */
    public function setUseLazyGhostObject(bool $flag): void
    {
        $this->useLazyGhostObject = $flag;
    }

    public function isLazyGhostObjectEnabled(): bool
    {
        return $this->useLazyGhostObject;
    }

    /**
     * Gets the logger callable.
     *
     * @return callable
     */
    public function getLoggerCallable()
    {
        return isset($this->_attributes['loggerCallable']) ? $this->_attributes['loggerCallable'] : null;
    }

    /**
     * Set the logger callable.
     *
     * @param callable $loggerCallable
     */
    public function setLoggerCallable($loggerCallable)
    {
        $this->_attributes['loggerCallable'] = $loggerCallable;
    }

    /**
     * Gets the profiler callable.
     *
     * @return callable
     */
    public function getProfilerCallable()
    {
        return isset($this->_attributes['profilerCallable']) ? $this->_attributes['profilerCallable'] : null;
    }

    /**
     * Set the profiler callable.
     *
     * @param callable $loggerCallable
     */
    public function setProfilerCallable($profilerCallable)
    {
        $this->_attributes['profilerCallable'] = $profilerCallable;
    }

    /**
     * Set the entity listener resolver.
     *
     * @since 2.4
     *
     * @param DefaultObjectListenerResolver $resolver
     */
    public function setObjectListenerResolver(DefaultObjectListenerResolver $resolver)
    {
        $this->_attributes['ObjectListenerResolver'] = $resolver;
    }

    /**
     * Get the entity listener resolver.
     *
     * @since 2.4
     *
     * @return DefaultObjectListenerResolver
     */
    public function getObjectListenerResolver()
    {
        if (!isset($this->_attributes['ObjectListenerResolver'])) {
            $this->_attributes['ObjectListenerResolver'] = new DefaultObjectListenerResolver();
        }

        return $this->_attributes['ObjectListenerResolver'];
    }

    /**
     * Define Parse connection parameters.
     *
     * @param array $parameters
     */
    public function setConnectionParameters(array $parameters)
    {
        $this->_attributes['connectionParams'] = $parameters;
    }

    /**
     * Get Parse connection parameters.
     *
     * @return array
     */
    public function getConnectionParameters()
    {
        if (!isset($this->_attributes['connectionParams'])) {
            throw new \Exception("Connection parameters must be defined.");
        }

        return $this->_attributes['connectionParams'];
    }

    /**
     * Gets the alwaysMaster.
     *
     * @return boolean
     */
    public function getAlwaysMaster()
    {
        return isset($this->_attributes['alwaysMaster']) ? $this->_attributes['alwaysMaster'] : true;
    }

    /**
     * Set the alwaysMaster.
     *
     * @param boolean $alwaysMaster
     */
    public function setAlwaysMaster($alwaysMaster)
    {
        $this->_attributes['alwaysMaster'] = $alwaysMaster;
    }

    public function getMetadataCache(): ?CacheItemPoolInterface
    {
        return $this->metadataCache;
    }

    public function setMetadataCache(CacheItemPoolInterface $cache): void
    {
        $this->metadataCache = $cache;
    }
}
